In [1]:
#载入数据处理必备的模组
import numpy as np
import pandas as pd

In [2]:
#载入数据
data=pd.read_csv("data/data.csv")
print(data.head())
print(len(data))



  stock_code       revenue  s_fa_eps_basic     du_profit  plus_net_invest_inc  \
0  000001.SZ  8.196800e+10          1.0600  0.000000e+00         0.000000e+00   
1  000002.SZ  1.170000e+11          1.0050  2.222772e+10         2.046834e+09   
2  000008.SZ  1.007329e+09          0.0434  1.776341e+08         0.000000e+00   
3  000060.SZ  1.482919e+10          0.3800  1.279332e+09         2.853988e+07   
4  000063.SZ  4.775730e+10          0.9300  5.884933e+09        -1.951700e+07   

   net_cash_flows_oper_act  net_cash_flows_inv_act  net_roe  total_roe  \
0            -1.530000e+11           -9.716200e+10   8.7813     0.6289   
1             6.474047e+09            1.392036e+10   9.5305     1.6026   
2            -9.947078e+07           -1.193312e+09   1.9528     1.5235   
3             7.571307e+08           -4.932751e+08   8.6684     4.9238   
4            -3.170483e+09           -4.387188e+09  12.6504     2.9854   

         RSI       VOL      WILLR         y      date  
0  52.970207

In [3]:
#分析数据的日期
date=data.loc[:,"date"]
date=date.tolist()
date=set(date)
date=list(date)
date=sorted(date)
print(date)




[20171207, 20180105, 20180209, 20180309, 20180412, 20180510, 20180608, 20180706, 20180803, 20180831, 20181006, 20181103, 20181201, 20190102, 20190206, 20190306, 20190404, 20190507, 20190605, 20190703, 20190731, 20190829, 20191003, 20191031, 20191128, 20191227, 20200201]


In [4]:
#准备数据输入和标签
data=data.set_index(["stock_code"])


#数据清洗，去除NAN

data=data.dropna()

x_data=data.drop(["date","y"],axis=1)
y_data=data.loc[:,"y"]




In [47]:
print(data)

                 revenue  s_fa_eps_basic     du_profit  plus_net_invest_inc  \
stock_code                                                                    
000001.SZ   8.196800e+10          1.0600  0.000000e+00         0.000000e+00   
000002.SZ   1.170000e+11          1.0050  2.222772e+10         2.046834e+09   
000008.SZ   1.007329e+09          0.0434  1.776341e+08         0.000000e+00   
000060.SZ   1.482919e+10          0.3800  1.279332e+09         2.853988e+07   
000063.SZ   4.775730e+10          0.9300  5.884933e+09        -1.951700e+07   
000069.SZ   1.936846e+10          0.5765  7.399214e+09         1.726553e+08   
000100.SZ   7.779557e+10          0.1561  5.067106e+09         5.876664e+08   
000157.SZ   1.786027e+10          0.1700  2.543303e+09         3.467468e+07   
000166.SZ   1.016370e+10          0.1800  0.000000e+00         9.991444e+07   
000333.SZ   1.170000e+11          2.3100  1.969210e+10         2.950820e+08   
000338.SZ   6.327634e+10          0.5800  8.127785e+

In [46]:
print(y_data)

stock_code
000001.SZ    0.035853
000002.SZ    0.028047
000008.SZ    0.050602
000060.SZ    0.019249
000063.SZ    0.068517
000069.SZ   -0.046674
000100.SZ   -0.049505
000157.SZ    0.037647
000166.SZ   -0.050909
000333.SZ    0.107063
000338.SZ    0.088274
000402.SZ   -0.020536
000413.SZ   -0.003181
000415.SZ    0.043557
000423.SZ   -0.003169
000425.SZ    0.233696
000503.SZ    0.339354
000538.SZ    0.067236
000559.SZ   -0.024059
000568.SZ    0.075650
000623.SZ   -0.034909
000625.SZ   -0.028244
000627.SZ   -0.070615
000630.SZ    0.047970
000651.SZ    0.058333
000671.SZ    0.151057
000686.SZ   -0.055495
000709.SZ   -0.040100
000723.SZ   -0.024896
000725.SZ    0.030466
               ...   
601788.SH    0.164875
601800.SH    0.062169
601818.SH    0.053619
601857.SH    0.046784
601866.SH    0.063927
601872.SH    0.024648
601877.SH    0.194763
601878.SH    0.211356
601881.SH    0.123762
601888.SH    0.152710
601898.SH    0.085714
601899.SH    0.217617
601901.SH    0.146409
601919.SH    0.042056

In [5]:
#对于数据进行预处理
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

#对输入数据进行处理，提取可以被机器学习接受的数组形式

x=x_data.values

#对数据进行归一化处理
nm_scaler=MinMaxScaler()
x=nm_scaler.fit_transform(x)

# 使用主成分分析，对数据作降维处理，提取10个关键的特征

pca=PCA(n_components=7)
x=pca.fit_transform(x)



#划分训练和测试数据集

train_x=x[0:5702]
test_x=x[5702:]



In [6]:
y=y_data.copy()
y=y.values
print(y)

[0.03585347 0.02804675 0.05060241 ... 0.14119923 0.12239444 0.23989218]


In [16]:
y[y>=0.04]=1
y[y<0.04]=0
print(y)

[0. 0. 1. ... 1. 1. 1.]


In [17]:



#划分训练和测试标签集

train_y=y[0:5702]
test_y=y[5702:]





In [18]:
# 构建最基础的机器学习KNN模型，对模型进行训练
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3,weights="distance")

knn.fit(train_x,train_y)
predict_train_y=knn.predict(train_x)




In [19]:
print(predict_train_y)

[0. 0. 1. ... 0. 0. 0.]


In [20]:
# 查看训练的拟合度

from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(train_y,predict_train_y))
cm=confusion_matrix(train_y,predict_train_y)
print(cm)


1.0
[[4263    0]
 [   0 1439]]


In [21]:
# 查看测试结果
predict_test_y=knn.predict(test_x)

print(accuracy_score(test_y,predict_test_y))
cm=confusion_matrix(test_y,predict_test_y)
print(cm)





0.5957642725598526
[[1132  226]
 [ 652  162]]


In [58]:
import tensorflow as tf
tf.__version__


'2.1.0'

In [61]:
import keras

Using TensorFlow backend.


In [22]:
#搭建ANN模型，载入必须的库

from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam


In [23]:
#搭建模型

model=Sequential([Dense(10,input_dim=7),Activation("tanh"),Dense(1),Activation("sigmoid")])

adam=Adam(lr=0.01)
model.compile(optimizer=adam,loss="mean_squared_error",metrics=["accuracy"])



In [24]:
#训练模型
model.fit(train_x,train_y,nb_epoch=100,batch_size=500)


C:\Users\tcmc\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
5702/5702 [==============================] - 0s 14us/step - loss: 0.2257 - accuracy: 0.6908
Epoch 2/100
5702/5702 [==============================] - 0s 2us/step - loss: 0.1893 - accuracy: 0.7478
Epoch 3/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1844 - accuracy: 0.7476
Epoch 4/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1836 - accuracy: 0.7480
Epoch 5/100
5702/5702 [==============================] - 0s 5us/step - loss: 0.1828 - accuracy: 0.7496
Epoch 6/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1822 - accuracy: 0.7496
Epoch 7/100
5702/5702 [==============================] - 0s 5us/step - loss: 0.1819 - accuracy: 0.7494
Epoch 8/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1817 - accuracy: 0.7504
Epoch 9/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1817 - accuracy: 0.7506
Epoch 10/100
5702/5702 [==============================] - 0s 3us/step - 

5702/5702 [==============================] - 0s 3us/step - loss: 0.1800 - accuracy: 0.7508
Epoch 80/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1800 - accuracy: 0.7501
Epoch 81/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1801 - accuracy: 0.7517
Epoch 82/100
5702/5702 [==============================] - 0s 3us/step - loss: 0.1799 - accuracy: 0.7508
Epoch 83/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1799 - accuracy: 0.7511
Epoch 84/100
5702/5702 [==============================] - 0s 3us/step - loss: 0.1799 - accuracy: 0.7506
Epoch 85/100
5702/5702 [==============================] - 0s 3us/step - loss: 0.1798 - accuracy: 0.7508
Epoch 86/100
5702/5702 [==============================] - 0s 4us/step - loss: 0.1798 - accuracy: 0.7504
Epoch 87/100
5702/5702 [==============================] - 0s 3us/step - loss: 0.1798 - accuracy: 0.7503
Epoch 88/100
5702/5702 [==============================] - 0s 3us/step - loss:

In [25]:
predict_test_y=model.predict(test_x)
print(predict_test_y)

[[0.19389993]
 [0.12399422]
 [0.20434143]
 ...
 [0.38359678]
 [0.26905566]
 [0.23956905]]


In [26]:
theta=0.6
predict_test_y[predict_test_y>=theta]=1
predict_test_y[predict_test_y<theta]=0

In [27]:
print(len(predict_test_y[predict_test_y==1]))

5


In [28]:
#测试模型表现
from sklearn.metrics import accuracy_score, confusion_matrix


#将量化预测结果进行阈值分类

acc=accuracy_score(test_y,predict_test_y)
cm=confusion_matrix(test_y,predict_test_y)

print(acc)
print(cm)


#查看统计结果


0.6275322283609577
[[1358    0]
 [ 809    5]]
